let personagem = {
    naturesa: {
        especie: [],
        ocupacao: [],
        atributo: [],
        asesorio: [],
    },
    comico: {
        especie: [
            "Água - viva",
            "Alpaca",
            "Anta",
            "Antílope",
            "Aranha",
            "Arara",
            "Arara - azul",
            "Ararajuba",
            "Arraia",
            "Avestruz",
            "Axalotl",
            "Baiacu",
            "Baleia",
            "Baleia - branca",
            "Barata",
            "Beija - flor",
            "Bem - te - vi",
            "Besouro",
            "Besouro hercules",
            "Bicho preguiça",
            "Bicho - pau",
            "Bisão",
            "Bode",
            "Boi - almiscarado",
            "Borboleta",
            "Boto cor - de - rosa",
            "Bufalo",
            "Búfalo africano",
            "Cabra",
            "Cachorro Daschund",
            "Cachorro Pug",
            "Calopsita",
            "Camaleão",
            "Camarão",
            "Camelo",
            "Canguru",
            "Cão",
            "Capivara",
            "Caracol",
            "Caramujo",
            "Carangueijo",
            "Carneiro",
            "Carrapato",
            "Castor",
            'Cavalo',
            "Cavalo - marinho",
            "Centopeia",
            "Cervo",
            "Cervo - do -Pantanal",
            "Chacal",
            "Chinchila",
            'Cisne',
            "Coala",
            'Cobra',
            "Cobra cascavel",
            "Coelho",
            "Coruja",
            "Coruja buraqueira",
            "Corvo",
            "Crocodilo",
            "Crocodilo - de - água - salgada",
            "Cupim",
            "Diabo - da - tasmânia",
            'Dodô',
            'Doninha',
            "Dragão - de - Komodo",
            "Elefante",
            "Elefante - de - sumatra",
            "Escaravelho",
            'Escorpião',
            'Esquilo',
            'Estrela - do -mar',
            "Falcão",
            "Flamingo",
        ],
        ocupacao: [
            "Protetor do Grupo",
            "Operário do Grupo",
        ],
        atributo: [
            'Agressivo',
            'Amedrontado',
            'Enraivecido',
            'Espreitando',
            'Ferido',
            'Fora de Si',
            'Forte',
            'Perdido',
            'Protetivo',
            'Recuperado',
            'Sorrateiro',
        ],
        asesorio: [
            'Com Cães',
            'Com Lobos',
            'Com Pássaros',
            'Em Volta de Árvores',
            'Em Volta de Flores',
            'Guardado por Animais Agressivos',
            'Na Natureza',
            'Protegendo Animais Fracos',
            'Protegido por Animais',
            'Protegido por Animais Pequenos',

        ],
    },
    fantasia: {
        especie: [
            'Anão',
            'Anjo',
            'Arvorídio',
            'Centauro',
            'Chimera',
            'Ciclope',
            'Demônio',
            'Diabrete',
            'Dragão',
            'Duende',
            'Elfo',
            'Elfo da Floresta',
            'Elfo das Sombras',
            'Esfinge',
            'Espectro',
            'Fada',
            'Fantasma',
            'Fauno',
            'Gigante',
            'Gnomo',
            'Goblin',
            'Golem',
            'Halfling',
            'Harpia',
            'Homem',
            'Humano',
            'Lamia',
            'Lich',
            'Lobisomem',
            'Máquina',
            'Monstro',
            'Ogro',
            'Orc',
            'Pássaro',
            'Pé Grande',
            'Pigmeu',
            'Sasquatch',
            'Sereia',
            'Serpente',
            'Tritão',
            'Troll',
            'Unicórnio',
            'Vampiro',
            'Zumbi'
        ],
        ocupacao: [
            'Acólito',
            'Acrobata',
            'Adivinho',
            'Alquimista',
            'Ancião',
            'Arcano',
            'Arqueiro',
            'Artesão',
            'Artífice',
            'Artista Marcial',
            'Assassino',
            'Aventureiro',
            'Bandido',
            'Bárbaro',
            'Bardo',
            'Batedor',
            'Bispo',
            'Capitão',
            'Cavaleiro',
            'Clérigo',
            'Curandeiro',
            'Druida',
            'Duelista',
            'Elementalista',
            'Encantador',
            'Encantador de Animais',
            'Escolástico',
            'Escudeiro',
            'Especialista',
            'Explorador',
            'Feiticeiro',
            'Gatuno',
            'Guarda',
            'Harpista',
            'Hermitão',
            'Hipnotista',
            'Ilusionista',
            'Invocador',
            'Lanceiro',
            'Mágico',
            'Mago',
            'Mercador',
            'Mercenário',
            'Mestre de Armadilhas',
            'Mestre de Armas',
            'Mímico',
            'Ministro',
            'Místico',
            'Mosqueteiro',
            'Necromante',
            'Ninja',
            'Oráculo',
            'Paladino',
            'Peregrino',
            'Pirata',
            'Piromante',
            'Psíquico',
            'Ranger',
            'Rebelde',
            'Samurai',
            'Sentinela',
            'Soldado',
            'Templário',
            'Valquírio',
            'Viajante',
            'Vidente',
            'Viking',
            'Warlock',
            'Xamã',
        ],
        atributo: [
            'Abençoado',
            'Agraciado',
            'Amaldiçoado',
            'Ambulante',
            'Bem Intencionado',
            'Benevolente',
            'Calado',
            'Caótico',
            'Comportado',
            'Conjurador',
            'Corajoso',
            'Curioso',
            'de Grande Beleza',
            'Deformado',
            'Desconhecido',
            'Desistente',
            'Elevado',
            'Encantado',
            'Enfeitiçado',
            'Errante',
            'Erudito',
            'Exótico',
            'Falante',
            'Famoso',
            'Forasteiro',
            'Iluminado',
            'Justiceiro',
            'Líder',
            'Mal Intencionado',
            'Maldoso',
            'Manipulador',
            'Ordeiro',
            'Ordenado',
            'Perdido',
            'Perfeccionista',
            'Perigoso',
            'Perseverante',
            'Perverso',
            'Poderoso',
            'Possuído',
            'Reconhecido',
            'Solitário',
            'Sorrateiro',
            'Suspeito',
            'Trevoso',
        ],
        asesorio: [
            'Acompanhado de Pássaros',
            'Bem Vestido',
            'Carregando Aquário',
            'Carregando Arma Gigante',
            'Carregando Caveiras',
            'Carregando Cesta de Frutas',
            'Carregando Escrituras',
            'Carregando Ferradura',
            'Carregando Martelo Encantado',
            'Carregando Runas Místicas',
            'Com Adaga',
            'Com Arco Mágico',
            'Com Armadura Arcana',
            'Com Artefato Raro',
            'Com Asas',
            'Com Brincos',
            'Com Cachimbo',
            'Com Cajado',
            'Com Candeladro',
            'Com Capacete',
            'Com Cetro',
            'Com Chapéu de Mago',
            'Com Cicatrizes',
            'Com Coroa',
            'Com Coroa de Flores',
            'Com Coroa de Folhas',
            'Com Correntes',
            'Com Enxada',
            'Com Espada',
            'Com Espada Iluminada',
            'Com Espíritos Circundando',
            'Com Facas Exóticas',
            'Com Flauta Tribal',
            'Com Foice',
            'Com Lança Exótica',
            'Com Lanterna',
            'Com Livro de Magia',
            'Com Luneta',
            'Com Machado',
            'Com Manopla',
            'Com Manto de Invisibilidade',
            'Com Martelo',
            'Com Máscara',
            'Com Olhos Luminosos',
            'Com Prisioneiro',
            'Com Raios',
            'Com Rosário',
            'Com Runas Tatuadas',
            'Com Saco de Luz',
            'Com Saco de Moedas',
            'Com Símbolos de Proteção',
            'Com Tatuagens Luminosas',
            'Com Tridente',
            'Com Varinha Mágica',
            'Com Vassoura',
            'Controlando Água',
            'Controlando Fogo',
            'Controlando Magma',
            'Controlando o Tempo',
            'Controlando Terra',
            'Controlando Vento',
            'Descalço',
            'Emanando Escuridão',
            'Envolto em orbes de luz',
            'Erradiando Luz',
            'Maltrapilho',
            'Portando Tesouro',
            'Portando Uma Relíquia',
            'Protegido por Animais',
            'Segurando Chaves',
            'Segurando Escudo',
            'Vestindo Botas Voadoras',
            'Vestindo Elmo',
        ],
    },
    medieval: {
        especie: [
            'Criança',
            'Garota',
            'Garoto',
            'Homem',
            'Mulher',
            'Quadrúpede',
        ],
        ocupacao: [
            'Adestrador',
            'Andarilho',
            'Aprendiz',
            'Armeiro',
            'Arqueiro',
            'Assassino',
            'Bardo',
            'Bobo - da - Corte',
            'Boticário',
            'Camponês',
            'Capitão',
            'Cavaleiro',
            'Charlatão',
            'Comandante',
            'Dançarino',
            'Escravo',
            'Escrivão',
            'Escudeiro',
            'Estudioso',
            'Faraó',
            'Ferreiro',
            'Gladiador',
            'Guarda',
            'Guerreiro',
            'Informante',
            'Inventor',
            'Ladrão',
            'Líder',
            'Lutador',
            'Matador',
            'Mercador',
            'Mercenário',
            'Mestre',
            'Minerador',
            'Monge',
            'Operário',
            'Padre',
            'Pedinte',
            'Protetor',
            'Sacerdote',
            'Servo',
            'Soldado',
            'Taverneiro',
            'Traficante',
            'Vassalo',
            'Vidente',
            'Vigia',
        ],
        atributo: ['Amputado',
            'Ardiloso',
            'Arrogante',
            'Atordoado',
            'Azarado',
            'Baderneiro',
            'Bondoso',
            'Calmo',
            'Campeão',
            'Cego',
            'Confiante',
            'Conquistador',
            'Consagrado',
            'Corajoso',
            'Debochado',
            'Deformado',
            'Derrotado',
            'Desconfiado',
            'Embriagado',
            'Enaltecido',
            'Enferrujado',
            'Enfraquecido',
            'Enfurecido',
            'Fiel',
            'Fora de Si',
            'Fortalecido',
            'Forte',
            'Humilhado',
            'Indiferente',
            'Influente',
            'Inteligente',
            'Jovem',
            'Maldoso',
            'Manco',
            'Manipulador',
            'Molhado',
            'Monarca',
            'Ornado',
            'Perigoso',
            'Pobre',
            'Pomposo',
            'Preguiçoso',
            'Protegido',
            'Rico',
            'Sábio',
            'Sagaz',
            'Sereno',
            'Soberano',
            'Sonolento',
            'Sorrateiro',
            'Sortudo',
            'Sujo',

            'Surdo',
            'Temido',
            'Traiçoeiro',
            'Traidor',
            'Velho',
            'Viajante',
            'Vitorioso',
        ],
        asesorio: [
            'Amarrado',
            'Amordaçado',
            'Bem Vestido',
            'Carregando Barris',
            'Com Arco e Flecha',
            'Com Arma Exótica',
            'Com Braço Tatuado',
            'Com Espada',
            'Com Espada Suja',
            'Com Instrumento Exótico',
            'Com Instrumento Musical',
            'Com Jóias',
            'Com Lança',
            'Com Machado Enferrujado',
            'Com Olhos Luminosos',
            'Com Olhos Vermelhos',
            'Com os Olhos Cobertos',
            'Com Rosto Tatuado',
            'Com Roupas Coloridas',
            'Com Roupas Exóticas',
            'Com Sacos',
            'Com Símbolos Arcanos',
            'Com Vestes Limpas',
            'Com Vestes Sujas',
            'De Armadura Leve',
            'De Armadura Nova',
            'De Armadura Pesada',
            'de Armadura Resulente',
            'De Armadura Velha',
            'De Capacete',
            'de Manto Ornado',
            'Levando Cordas',
            'Levando Pergaminhos',
            'Maltrapilho',
            'Sem Olhos',
        ],
    }
}