let personagem = {
    naturesa: {
        especie: [],
        ocupacao: [],
        atributo: [],
        asesorio: [],
    },
    comico: {
        especie: [
            "Água - viva",
            "Alpaca",
            "Anta",
            "Antílope",
            "Aranha",
            "Arara",
            "Arara - azul",
            "Ararajuba",
            "Arraia",
            "Avestruz",
            "Axalotl",
            "Baiacu",
            "Baleia",
            "Baleia - branca",
            "Barata",
            "Beija - flor",
            "Bem - te - vi",
            "Besouro",
            "Besouro hercules",
            "Bicho preguiça",
            "Bicho - pau",
            "Bisão",
            "Bode",
            "Boi - almiscarado",
            "Borboleta",
            "Boto cor - de - rosa",
            "Bufalo",
            "Búfalo africano",
            "Cabra",
            "Cachorro Daschund",
            "Cachorro Pug",
            "Calopsita",
            "Camaleão",
            "Camarão",
            "Camelo",
            "Canguru",
            "Cão",
            "Capivara",
            "Caracol",
            "Caramujo",
            "Carangueijo",
            "Carneiro",
            "Carrapato",
            "Castor",
            'Cavalo',
            "Cavalo - marinho",
            "Centopeia",
            "Cervo",
            "Cervo - do -Pantanal",
            "Chacal",
            "Chinchila",
            'Cisne',
            "Coala",
            'Cobra',
            "Cobra cascavel",
            "Coelho",
            "Coruja",
            "Coruja buraqueira",
            "Corvo",
            "Crocodilo",
            "Crocodilo - de - água - salgada",
            "Cupim",
            "Diabo - da - tasmânia",
            'Dodô',
            'Doninha',
            "Dragão - de - Komodo",
            "Elefante",
            "Elefante - de - sumatra",
            "Escaravelho",
            'Escorpião',
            'Esquilo',
            'Estrela - do -mar',
            "Falcão",
            "Flamingo",
        ],
        ocupacao: [
            "Protetor do Grupo",
            "Operário do Grupo",
        ],
        atributo: [
            'Agressivo',
            'Amedrontado',
            'Enraivecido',
            'Espreitando',
            'Ferido',
            'Fora de Si',
            'Forte',
            'Perdido',
            'Protetivo',
            'Recuperado',
            'Sorrateiro',
        ],
        asesorio: [
            'Com Cães',
            'Com Lobos',
            'Com Pássaros',
            'Em Volta de Árvores',
            'Em Volta de Flores',
            'Guardado por Animais Agressivos',
            'Na Natureza',
            'Protegendo Animais Fracos',
            'Protegido por Animais',
            'Protegido por Animais Pequenos',

        ],
    },
    fantasia: {
        especie: [],
        ocupacao: [],
        atributo: [],
        asesorio: [],
    },
    medieval: {
        especie: [],
        ocupacao: [],
        atributo: [],
        asesorio: [],
    }
}